
team_abbr_lookup = {
    "Toronto Raptors": "TOR",
    "Brooklyn Nets": "BRK",
    "New York Knicks": "NYK",
    "Boston Celtics": "BOS",
    "Philadelphia 76ers": "PHI",
    "Indiana Pacers": "IND",
    "Chicago Bulls": "CHI",
    "Cleveland Cavaliers": "CLE",
    "Detroit Pistons": "DET",
    "Milwaukee Bucks": "MIL",
    "Miami Heat": "MIA",
    "Washington Wizards": "WAS",
    "Charlotte Bobcats": "CHA",
    "Charlotte Hornets": "CHA",
    "Atlanta Hawks": "ATL",
    "Orlando Magic": "ORL",
    "Oklahoma City Thunder": "OKC",
    "Portland Trail Blazers": "POR",
    "Minnesota Timberwolves": "MIN",
    "Denver Nuggets": "DEN",
    "Utah Jazz": "UTA",
    "Los Angeles Clippers": "LAC",
    "Golden State Warriors": "GSW",
    "Phoenix Suns": "PHO",
    "Sacramento Kings": "SAC",
    "Los Angeles Lakers": "LAL",
    "San Antonio Spurs": "SAS",
    "Houston Rockets": "HOU",
    "Memphis Grizzlies": "MEM",
    "Dallas Mavericks": "DAL",
    "New Orleans Pelicans": "NOP"
}


abbr_team_lookup = {
    "TOR": "Toronto Raptors",
    "BRK": "Brooklyn Nets",
    "NYK": "New York Knicks",
    "BOS": "Boston Celtics",
    "PHI": "Philadelphia 76ers",
    "IND": "Indiana Pacers",
    "CHI": "Chicago Bulls",
    "CLE": "Cleveland Cavaliers",
    "DET": "Detroit Pistons",
    "MIL": "Milwaukee Bucks",
    "MIA": "Miami Heat",
    "WAS": "Washington Wizards",
    "CHA": "Charlotte Hornets",
    "ATL": "Atlanta Hawks",
    "ORL": "Orlando Magic",
    "OKC": "Oklahoma City Thunder",
    "POR": "Portland Trail Blazers",
    "MIN": "Minnesota Timberwolves",
    "DEN": "Denver Nuggets",
    "UTA": "Utah Jazz",
    "LAC": "Los Angeles Clippers",
    "GSW": "Golden State Warriors",
    "PHO": "Phoenix Suns",
    "SAC": "Sacramento Kings",
    "LAL": "Los Angeles Lakers",
    "SAS": "San Antonio Spurs",
    "HOU": "Houston Rockets",
    "MEM": "Memphis Grizzlies",
    "DAL": "Dallas Mavericks",
    "NOP": "New Orleans Pelicans"
}


oddsshark_team_id_lookup = {
    "Toronto Raptors": 20742,
    "Brooklyn Nets": 20749,
    "New York Knicks": 20747,
    "Boston Celtics": 20722,
    "Philadelphia 76ers": 20731,
    "Indiana Pacers": 20737,
    "Chicago Bulls": 20732,
    "Cleveland Cavaliers": 20735,
    "Detroit Pistons": 20743,
    "Milwaukee Bucks": 20725,
    "Miami Heat": 20726,
    "Washington Wizards": 20746,
    "Charlotte Bobcats": 20751,
    "Atlanta Hawks": 20734,
    "Orlando Magic": 20750,
    "Oklahoma City Thunder": 20728,
    "Portland Trail Blazers": 20748,
    "Minnesota Timberwolves": 20744,
    "Denver Nuggets": 20723,
    "Utah Jazz": 20738,
    "Los Angeles Clippers": 20736,
    "Golden State Warriors": 20741,
    "Phoenix Suns": 20730,
    "Sacramento Kings": 20745,
    "Los Angeles Lakers": 20739,
    "San Antonio Spurs": 20724,
    "Houston Rockets": 20740,
    "Memphis Grizzlies": 20729,
    "Dallas Mavericks": 20727,
    "New Orleans Pelicans": 20733
}


oddsshark_city_lookup = {
    "Toronto": "Toronto Raptors",
    "Brooklyn": "Brooklyn Nets",
    "New York": "New York Knicks",
    "Boston": "Boston Celtics",
    "Philadelphia": "Philadelphia 76ers",
    "Indiana": "Indiana Pacers",
    "Chicago": "Chicago Bulls",
    "Cleveland": "Cleveland Cavaliers",
    "Detroit": "Detroit Pistons",
    "Milwaukee": "Milwaukee Bucks",
    "Miami": "Miami Heat",
    "Washington": "Washington Wizards",
    "Charlotte": "Charlotte Hornets",
    "Atlanta": "Atlanta Hawks",
    "Orlando": "Orlando Magic",
    "Oklahoma City": "Oklahoma City Thunder",
    "Portland": "Portland Trail Blazers",
    "Minnesota": "Minnesota Timberwolves",
    "Denver": "Denver Nuggets",
    "Utah": "Utah Jazz",
    "LA Clippers": "Los Angeles Clippers",
    "Golden State": "Golden State Warriors",
    "Phoenix": "Phoenix Suns",
    "Sacramento": "Sacramento Kings",
    "LA Lakers": "Los Angeles Lakers",
    "San Antonio": "San Antonio Spurs",
    "Houston": "Houston Rockets",
    "Memphis": "Memphis Grizzlies",
    "Dallas": "Dallas Mavericks",
    "New Orleans": "New Orleans Pelicans"

}
